### ISSUE TITLE
Crash on startup w/optifabric shaders 1.15.2

### ISSUE THREAD

**Issue by abouteiller** [ToroCraft/ToroHealth#46]
Crash on startup w/optifabric shaders on Minecraft 1.15.2. This appears to be related to having a Shader active when Torohealth initially loads, because  it works if shaders are set after load. 

1. Starting the game with Optifabric and Optifine 1.15 pre13; and ToroHealth: the game crashes with the linked error
2. Starting the game w/o Optifabric w/ ToroHealth works fine
3. Starting the game with Optifabric and Optifine w/o ToroHealth works fine
4. Starting the game with Optifabric and Optifine and Torohealth w/o a shader set in the options works fine
5. After the game is loaded with Optifine and Torohealth, a shader can be set and it will work.

```
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 4/24/20, 1:40 AM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
at net.torocraft.torohealth.util.InWorldEntityBars.addEntity(InWorldEntityBars.java:33)
at net.minecraft.class_898.handler$zjf000$postRender(class_898.java:1065)
at net.minecraft.class_898.method_3954(class_898.java:283)
at net.minecraft.class_761.method_22977(class_761.java:1841)
at net.optifine.shaders.ShadersRender.renderShadowMap(ShadersRender.java:393)
at net.optifine.shaders.Shaders.beginRender(Shaders.java:4248)
at net.minecraft.class_757.method_3188(class_757.java:928)
at net.minecraft.class_757.method_3192(class_757.java:688)
at net.minecraft.class_310.method_1523(class_310.java:989)
at net.minecraft.class_310.method_1514(class_310.java:619)
at net.minecraft.client.main.Main.main(Main.java:204)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
at org.multimc.EntryPoint.listen(EntryPoint.java:143)
at org.multimc.EntryPoint.main(EntryPoint.java:34)
```

```
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
at net.torocraft.torohealth.util.InWorldEntityBars.addEntity(InWorldEntityBars.java:33)
at net.minecraft.class_898.handler$zjf000$postRender(class_898.java:1065)
at net.minecraft.class_898.method_3954(class_898.java:283)
at net.minecraft.class_761.method_22977(class_761.java:1841)
at net.optifine.shaders.ShadersRender.renderShadowMap(ShadersRender.java:393)
at net.optifine.shaders.Shaders.beginRender(Shaders.java:4248)
at net.minecraft.class_757.method_3188(class_757.java:928)

-- Affected level --
Details:
Chunk stats: Client Chunk Cache: 1369, 441
Level dimension: minecraft:overworld
Level name: MpServer
Level seed: 6742137923171255024
Level generator: ID 00 - default, ver 1. Features enabled: false
Level generator options: {}
Level spawn location: World: (-240,71,64), Chunk: (at 0,4,0 in -15,4; contains blocks -240,0,64 to -225,255,79), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
Level time: 3985891 game time, 2707660 day time
Known server brands: 
Level was modded: false
Level storage version: 0x00000 - Unknown?
Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Server brand: fabric
Server type: Integrated singleplayer server
Stacktrace:
at net.minecraft.class_638.method_8538(class_638.java:611)
at net.minecraft.class_310.method_1587(class_310.java:1921)
at net.minecraft.class_310.method_1514(class_310.java:639)
at net.minecraft.client.main.Main.main(Main.java:204)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
at org.multimc.EntryPoint.listen(EntryPoint.java:143)
at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
Minecraft Version: 1.15.2
Minecraft Version ID: 1.15.2
Operating System: Windows 10 (amd64) version 10.0
Java Version: 11.0.7, Eclipse OpenJ9
Java VM Version: Eclipse OpenJ9 VM (JRE 11 Windows 10 amd64-64-Bit Compressed References 20200422_551 (JIT enabled, AOT enabled)
OpenJ9   - 05fa2d361
OMR      - d4365f371
JCL      - 838028fc9d based on jdk-11.0.7+10), Eclipse OpenJ9
Memory: 378718496 bytes (361 MB) / 1916010496 bytes (1827 MB) up to 10737418240 bytes (10240 MB)
CPUs: 12
JVM Flags: 6 total; -Xoptionsfile=C:\Program Files\AdoptOpenJDK\jdk-11.0.7.10-openj9\lib\options.default -Xlockword:mode=default,noLockword=java/lang/String,noLockword=java/util/MapEntry,noLockword=java/util/HashMap$Entry,noLockword=org/apache/harmony/luni/util/ModifiedMap$Entry,noLockword=java/util/Hashtable$Entry,noLockword=java/lang/invoke/MethodType,noLockword=java/lang/invoke/MethodHandle,noLockword=java/lang/invoke/CollectHandle,noLockword=java/lang/invoke/ConstructorHandle,noLockword=java/lang/invoke/ConvertHandle,noLockword=java/lang/invoke/ArgumentConversionHandle,noLockword=java/lang/invoke/AsTypeHandle,noLockword=java/lang/invoke/ExplicitCastHandle,noLockword=java/lang/invoke/FilterReturnHandle,noLockword=java/lang/invoke/DirectHandle,noLockword=java/lang/invoke/ReceiverBoundHandle,noLockword=java/lang/invoke/DynamicInvokerHandle,noLockword=java/lang/invoke/FieldHandle,noLockword=java/lang/invoke/FieldGetterHandle,noLockword=java/lang/invoke/FieldSetterHandle,noLockword=java/lang/invoke/StaticFieldGetterHandle,noLockword=java/lang/invoke/StaticFieldSetterHandle,noLockword=java/lang/invoke/IndirectHandle,noLockword=java/lang/invoke/InterfaceHandle,noLockword=java/lang/invoke/VirtualHandle,noLockword=java/lang/invoke/PrimitiveHandle,noLockword=java/lang/invoke/InvokeExactHandle,noLockword=java/lang/invoke/InvokeGenericHandle,noLockword=java/lang/invoke/VarargsCollectorHandle,noLockword=java/lang/invoke/ThunkTuple -Xjcl:jclse29 -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms1024m -Xmx10240m
Fabric Mods: 
authme: Auth Me 1.1.1
bettergraves: Better Graves 0.2.1-beta.2
cloth-config2: Cloth Config v2 2.10
com_moandjiezana_toml_toml4j: toml4j 0.7.2
cotton: Cotton 1.0.2
cotton-cauldron: Cotton Cauldron 1.0.0-rc.6
cotton-commons: Cotton Commons 1.0.0-rc.4
cotton-config: Cotton Config 1.0.0-rc.7
cotton-datapack: Cotton Datapack 1.0.1
cotton-logging: Cotton Logging 1.0.0-rc.4
cotton-player-events: Cotton Player Events 1.0.2
couplings: Couplings 1.3.1
fabric: Fabric API 0.5.1+build.294-1.15
fabric-api-base: Fabric API Base 0.1.2+b7f9825d0c
fabric-biomes-v1: Fabric Biomes (v1) 0.1.5+3b05f68e0c
fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea890c
fabric-commands-v0: Fabric Commands (v0) 0.1.2+b7f9825d0c
fabric-containers-v0: Fabric Containers (v0) 0.1.3+b7f9825d0c
fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.3+b7f9825d0c
fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d0c
fabric-dimensions-v1: fabric-dimensions-v1 0.3.0+2ad156310c
fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.0+fac69e320c
fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.1.2+b7f9825d0c
fabric-item-groups-v0: Fabric Item Groups (v0) 0.1.6+ec40b2e10c
fabric-keybindings-v0: Fabric Key Bindings (v0) 0.1.1+dfdb52d60c
fabric-language-kotlin: Fabric Language Kotlin 1.3.61+build.2
fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.5+e08a73050c
fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.1+b7f9825d0c
fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d60c
fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.3+e08a73050c
fabric-networking-v0: Fabric Networking (v0) 0.1.7+12515ed90c
fabric-object-builders-v0: Fabric Object Builders (v0) 0.1.3+e4c9a9c30c
fabric-particles-v1: fabric-particles-v1 0.1.1+dfdb52d60c
fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.2.6+f3d8141b0c
fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.10+f08b61330c
fabric-renderer-indigo: Fabric Renderer - Indigo 0.2.23+9290e2ed0c
fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a600c
fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d0c
fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.6+12515ed90c
fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+534104900c
fabric-rendering-v1: Fabric Rendering (v1) 0.1.0+534104900c
fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.1.10+06c939b30c
fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.1.3+abd915800c
fabric-textures-v0: Fabric Textures (v0) 1.0.4+821cdba70c
fabricloader: Fabric Loader 0.8.2+build.194
fermion-modkeys: Fermion Modifier Keys 1.5.148
harvest: Harvest 1.0.4
jankson: Jankson 2.0.1+j1.2.0
jumpoverfences: JumpOverFences 1.15-0.0.1
libcd: LibCapableData 2.2.2+1.15.2
lithium: Lithium 0.4.6
malilib: MaLiLib 0.10.0-dev.20+arne.6
me_shedaniel_cloth_basic-math: basic-math 0.3.0
minecraft: Minecraft 1.15.2
minihud: MiniHUD 0.19.0-dev.20200121.203515
mm: Manningham Mills 2.0
modmenu: Mod Menu 1.10.2+build.32
optifabric: Optifabric 1.0.0-beta8
org_jetbrains_annotations: annotations 17.0.0
org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.3.61
org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.3.61
org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.3.61
org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.3.61
org_jetbrains_kotlinx_kotlinx-coroutines-core: kotlinx-coroutines-core 1.3.3
org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.3.3
org_slf4j_slf4j-api: slf4j-api 1.7.30
org_slf4j_slf4j-simple: slf4j-simple 1.7.30
org_zeroturnaround_zt-zip: zt-zip 1.14
phosphor: Phosphor 0.5.2+build.6
strongandfairanvils: Strong and Fair Anvils 0.3.0+1.15
terraform: Terraform 1.4.3+build.29
terrestria: Terrestria 1.2.1+build.29
tinyconfig: TinyConfig 1.1.2
torohealth: ToroHealth Damage Indicators 1.15.1-fabric-1
traverse: Traverse 2.1.11+build.23
trees-do-not-float: Trees Do Not Float 1.8.69
tweakeroo: Tweakeroo 0.10.0-dev.20200320.230739
voxelmap: VoxelMap 1.9.16
waila: Hwyla 1.9.22
wrenchable: Wrenchable 0.2.2+1.15.2
wrenchanything: Wrench Anything 1.1.3+1.15.2
Launched Version: MultiMC5
Backend library: LWJGL version 3.2.2 build 10
Backend API: Radeon RX 580 Series GL version 4.6.13587 Compatibility Profile Context 20.4.2 26.20.15029.27016, ATI Technologies Inc.
GL Caps: Using framebuffer using OpenGL 3.0
Using VBOs: Yes
Is Modded: Definitely; Client brand changed to 'fabric'
Type: Client (map_client.txt)
Resource Packs: vanilla, optifine, file/VoxelMap-ThinFrame.zip, file/Monsterley_128_15_200405.zip, file/VanillaTweaks_r429528.zip, file/Original+Art+1.15.zip, file/roboto-bold.zip
Current Language: English (US)
CPU: 12x AMD Ryzen 5 3600 6-Core Processor 
OptiFine Version: OptiFine_1.15.2_HD_U_G1_pre13
OptiFine Build: 20200401-232147
Render Distance Chunks: 16
Mipmaps: 4
Anisotropic Filtering: 1
Antialiasing: 0
Multitexture: false
Shaders: Sildurs Enhanced Default v1.10.zip
OpenGlVersion: 4.6.13587 Compatibility Profile Context 20.4.2 26.20.15029.27016
OpenGlRenderer: Radeon RX 580 Series
OpenGlVendor: ATI Technologies Inc.
CpuCount: 12
```

**Comment by TNThacker2015** [comment]
I am also experiencing this crash.

**Comment by Motschen** [comment]
Here's a fixed jar (unpack the zip)
[torohealth-1.15.1-fabric-fixed.zip](https://github.com/ToroCraft/ToroHealth/files/4703176/torohealth-1.15.1-fabric-fixed.zip)

**Comment by abouteiller** [comment]
@Motschen that's grand! Maybe you could open a PR with the changes so that it gets propagated to the main release.

**Comment by Motschen** [comment]
I probably won't be doing a PR here, since I just removed all the code of in-world-healthbars, an unimplemented feature, which should be finished instead of removing it.

**Comment by frodare** [comment]
Closing this as work is focused on 1.16.4
