### ISSUE TITLE
Crash on Forge 1.16.3

### ISSUE THREAD

**Issue by VL4DST3R** [ToroCraft/ToroHealth#57]
I get the following error when loading a map:

```
[02Oct2020 02:08:18.989] [Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: net.minecraft.client.Minecraft.getInstance()Lnet/minecraft/client/Minecraft;
	Index: 1
	Listeners:
		0: LOWEST
		1: ASM: class fr.lnzl.tdi.TextDamageIndicators onLivingDamageEvent(Lnet/minecraftforge/event/entity/living/LivingDamageEvent;)V
java.lang.NoSuchMethodError: net.minecraft.client.Minecraft.getInstance()Lnet/minecraft/client/Minecraft;
	at fr.lnzl.tdi.TextDamageIndicators.onLivingDamageEvent(TextDamageIndicators.java:36)
	at net.minecraftforge.eventbus.ASMEventHandler_25_TextDamageIndicators_onLivingDamageEvent_LivingDamageEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297)
	at net.minecraftforge.common.ForgeHooks.onLivingDamage(ForgeHooks.java:334)
	at net.minecraft.entity.LivingEntity.func_70665_d(LivingEntity.java:1483)
	at net.minecraft.entity.LivingEntity.func_70097_a(LivingEntity.java:984)
	at net.minecraft.entity.passive.BatEntity.func_70097_a(SourceFile:217)
	at net.minecraft.entity.Entity.func_70044_A(Entity.java:467)
	at net.minecraft.entity.Entity.func_70030_z(Entity.java:429)
	at net.minecraft.entity.LivingEntity.func_70030_z(LivingEntity.java:295)
	at net.minecraft.entity.MobEntity.func_70030_z(MobEntity.java:322)
	at net.minecraft.entity.Entity.func_70071_h_(Entity.java:387)
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2113)
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:430)
	at net.minecraft.entity.passive.BatEntity.func_70071_h_(SourceFile:117)
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:606)
	at net.minecraft.world.server.ServerWorld$$Lambda$6146/1273170010.accept(Unknown Source)
	at net.minecraft.world.World.func_217390_a(World.java:554)
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:399)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:846)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:782)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:120)
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:637)
	at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:229)
	at net.minecraft.server.MinecraftServer$$Lambda$5289/145423728.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

[02Oct2020 02:08:18.996] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
net.minecraft.crash.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:850) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:782) ~[?:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:120) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:637) [?:?]
	at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:229) [?:?]
	at net.minecraft.server.MinecraftServer$$Lambda$5289/145423728.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.NoSuchMethodError: net.minecraft.client.Minecraft.getInstance()Lnet/minecraft/client/Minecraft;
	at fr.lnzl.tdi.TextDamageIndicators.onLivingDamageEvent(TextDamageIndicators.java:36) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler_25_TextDamageIndicators_onLivingDamageEvent_LivingDamageEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.3-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.3-service.jar:?]
	at net.minecraftforge.common.ForgeHooks.onLivingDamage(ForgeHooks.java:334) ~[?:?]
	at net.minecraft.entity.LivingEntity.func_70665_d(LivingEntity.java:1483) ~[?:?]
	at net.minecraft.entity.LivingEntity.func_70097_a(LivingEntity.java:984) ~[?:?]
	at net.minecraft.entity.passive.BatEntity.func_70097_a(SourceFile:217) ~[?:?]
	at net.minecraft.entity.Entity.func_70044_A(Entity.java:467) ~[?:?]
	at net.minecraft.entity.Entity.func_70030_z(Entity.java:429) ~[?:?]
	at net.minecraft.entity.LivingEntity.func_70030_z(LivingEntity.java:295) ~[?:?]
	at net.minecraft.entity.MobEntity.func_70030_z(MobEntity.java:322) ~[?:?]
	at net.minecraft.entity.Entity.func_70071_h_(Entity.java:387) ~[?:?]
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2113) ~[?:?]
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:430) ~[?:?]
	at net.minecraft.entity.passive.BatEntity.func_70071_h_(SourceFile:117) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:606) ~[?:?]
	at net.minecraft.world.server.ServerWorld$$Lambda$6146/1273170010.accept(Unknown Source) ~[?:?]
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:399) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:846) ~[?:?]
	... 6 more
```

**Comment by frodare** [comment]
Please let me know if you are still getting this error on the latest version and if it still happens if ToroHealth is the only mod loaded.
